version: "3"

services:
  service-registry:
    build: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - movie-app
    environment:
      server.port: 8761
      SPRING_APPLICATION_NAME: service-registry
      SPRING_PROFILES_ACTIVE: docker
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/

  movie-catalog-service:
    build: movie-catalog-service
    container_name:  movie-catalog-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    networks:
      - movie-app
    environment:
      server.port: 8081
      SPRING_APPLICATION_NAME: movie-catalog-service
      SPRING_PROFILES_ACTIVE: docker
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    links:
     - service-registry

  movie-info-service:
    build: movie-info-service
    container_name:  movie-info-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
    networks:
      - movie-app
    environment:
      server.port: 8082
      SPRING_APPLICATION_NAME: movie-info-service
      SPRING_PROFILES_ACTIVE: docker
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    links:
     - service-registry

  rating-data-service:
    build: rating-data-service
    container_name:  rating-data-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    networks:
      - movie-app
    environment:
      server.port: 8083
      SPRING_APPLICATION_NAME: rating-data-service
      SPRING_PROFILES_ACTIVE: docker
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    links:
     - service-registry
     
networks:
  movie-app:
    name: movie-app
    driver: bridge